import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { compile } from 'json-schema-to-typescript';

import type { IR, JSONSchema, Operation } from '../ir.js';
import { checkNameCollisions, toClassName, toMethodName, toTypeName } from './names.js';

export interface EmitterOptions {
  packageName: string;
  adapter: string;
  loose: boolean;
  outDir: string;
  config: unknown;
  warnings?: string[];
}

interface EmittedOperation {
  rawName: string;
  description?: string;
  methodName: string;
  typeName: string;
  inputTypeName: string;
  outputTypeName?: string;
}

const TYPE_HEADER = '// AUTO-GENERATED by McPiler — do not edit manually';
const STRICT_CONTENT_RETURN = 'Array<TextContent | ImageContent | AudioContent | unknown>';

function indentBlock(value: string, spaces: number): string {
  const indent = ' '.repeat(spaces);
  return value
    .split('\n')
    .map((line) => (line ? `${indent}${line}` : line))
    .join('\n');
}

function escapeDocLine(line: string): string {
  return line.replace(/\*\//g, '*\\/');
}

function renderJsDoc(description: string | undefined, remarks: string | undefined): string {
  if (!description && !remarks) {
    return '';
  }

  const lines = ['  /**'];

  if (description) {
    for (const line of description.split(/\r?\n/)) {
      lines.push(`   * ${escapeDocLine(line)}`);
    }
  }

  if (description && remarks) {
    lines.push('   *');
  }

  if (remarks) {
    lines.push(`   * @remarks ${escapeDocLine(remarks)}`);
  }

  lines.push('   */');
  return `${lines.join('\n')}\n`;
}

function getUntypedRemarks(loose: boolean): string {
  return loose
    ? 'No outputSchema declared — output coerced to string. Type accuracy not guaranteed.'
    : 'No outputSchema declared — return type reflects possible content shapes.';
}

function getReturnType(operation: EmittedOperation, loose: boolean): string {
  if (operation.outputTypeName) {
    return operation.outputTypeName;
  }

  return loose ? 'string' : STRICT_CONTENT_RETURN;
}

function renderMethod(operation: EmittedOperation, loose: boolean): string {
  const jsDoc = renderJsDoc(
    operation.description,
    operation.outputTypeName ? undefined : getUntypedRemarks(loose),
  );
  const returnType = getReturnType(operation, loose);

  const body = operation.outputTypeName
    ? [
        '    await this.#ready;',
        `    const result = await this.#transport.call(${JSON.stringify(operation.rawName)}, input);`,
        `    return result.structured as ${operation.outputTypeName};`,
      ]
    : loose
      ? [
          '    await this.#ready;',
          `    const result = await this.#transport.call(${JSON.stringify(operation.rawName)}, input);`,
          '    const first = result.content[0];',
          '    if (typeof first === \x27object\x27 && first !== null && \x27text\x27 in first) {',
          '      return String((first as { text: unknown }).text);',
          '    }',
          '    return String(first ?? \x27\x27);',
        ]
      : [
          '    await this.#ready;',
          `    const result = await this.#transport.call(${JSON.stringify(operation.rawName)}, input);`,
          `    return result.content as ${STRICT_CONTENT_RETURN};`,
        ];

  return `${jsDoc}  async ${operation.methodName}(input: ${operation.inputTypeName}): Promise<${returnType}> {\n${body.join(
    '\n',
  )}\n  }`;
}

async function compileType(schema: JSONSchema, typeName: string): Promise<string> {
  return compile(schema as Parameters<typeof compile>[0], typeName, {
    bannerComment: '',
    style: { singleQuote: true },
    additionalProperties: false,
  });
}

async function renderTypesFile(ir: IR, operations: EmittedOperation[]): Promise<string> {
  if (operations.length === 0) {
    return `${TYPE_HEADER}\n`;
  }

  const blocks = await Promise.all(
    operations.map(async (operation, index) => {
      const originalOperation = ir.operations[index] as Operation;
      const parts = [`/* Operation: ${operation.rawName} */`];

      parts.push((await compileType(originalOperation.inputSchema, operation.inputTypeName)).trim());

      if (operation.outputTypeName && originalOperation.outputSchema) {
        parts.push((await compileType(originalOperation.outputSchema, operation.outputTypeName)).trim());
      }

      return parts.join('\n\n');
    }),
  );

  return `${TYPE_HEADER}\n\n${blocks.join('\n\n')}\n`;
}

function renderClientFile(options: EmitterOptions, operations: EmittedOperation[]): string {
  const className = toClassName(options.packageName);
  const typeImports = operations.flatMap((operation) =>
    operation.outputTypeName
      ? [operation.inputTypeName, operation.outputTypeName]
      : [operation.inputTypeName],
  );
  const needsContentImports = operations.some((operation) => !operation.outputTypeName && !options.loose);
  const serializedConfig = JSON.stringify(options.config, null, 2);
  const methodBlocks = operations.map((operation) => renderMethod(operation, options.loose));

  const lines = [TYPE_HEADER, '', "import { McpTransport } from '@mcpiler/runtime-mcp';"];

  if (needsContentImports) {
    lines.push("import type { TextContent, ImageContent, AudioContent } from '@mcpiler/runtime-mcp';");
  }

  if (typeImports.length > 0) {
    lines.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
  }

  lines.push('', `export class ${className} {`, '  #transport: McpTransport;', '  #ready: Promise<void>;', '', '  constructor() {');
  lines.push(`    this.#transport = new McpTransport(${indentBlock(serializedConfig, 6).trimStart()});`);
  lines.push('    this.#ready = this.#transport.connect();');
  lines.push("    process.on('exit', () => this.#transport.kill());");
  lines.push('  }', '', '  async [Symbol.asyncDispose](): Promise<void> {', '    await this.#transport.disconnect();', '  }');

  if (methodBlocks.length > 0) {
    lines.push('', methodBlocks.join('\n\n'));
  }

  lines.push('}', '');

  return lines.join('\n');
}

function renderPackageJson(options: EmitterOptions): string {
  return `${JSON.stringify(
    {
      name: options.packageName,
      version: '0.1.0',
      type: 'module',
      main: './dist/client.js',
      types: './dist/client.d.ts',
      scripts: {
        build: 'tsc',
      },
      dependencies: {
        '@mcpiler/runtime-mcp': '*',
      },
      devDependencies: {
        typescript: '^5.5.0',
        '@types/node': '^20.0.0',
      },
    },
    null,
    2,
  )}\n`;
}

function renderTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        lib: ['ES2022', 'ESNext.Disposable'],
        strict: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        esModuleInterop: true,
        skipLibCheck: true,
        rootDir: 'src',
        outDir: 'dist',
      },
      include: ['src'],
    },
    null,
    2,
  )}\n`;
}

function renderReadme(options: EmitterOptions, operations: EmittedOperation[]): string {
  const className = toClassName(options.packageName);
  const usageLines = [
    '## Usage',
    '',
    '```ts',
    `import { ${className} } from '${options.packageName}';`,
    '',
    `await using client = new ${className}();`,
  ];

  if (operations[0]) {
    usageLines.push(`const result = await client.${operations[0].methodName}({} as ${operations[0].inputTypeName});`);
  }

  usageLines.push('```');

  const sections = [
    `# ${options.packageName}`,
    '',
    'Generated by [McPiler](https://github.com/parleon/McPiler).',
    '',
    ...usageLines,
    '',
    '## Operations',
    '',
  ];

  if (operations.length === 0) {
    sections.push('_No operations were generated._');
  } else {
    sections.push(
      operations
        .map((operation) => {
          const signature = `### \`${operation.methodName}(input: ${operation.inputTypeName}): Promise<${getReturnType(operation, options.loose)}>\``;
          const details = [signature];

          if (operation.description) {
            details.push('', operation.description);
          }

          return details.join('\n');
        })
        .join('\n\n---\n\n'),
    );
  }

  if (options.warnings && options.warnings.length > 0) {
    sections.push('', '## ⚠️ Warnings', '');
    for (const warning of options.warnings) {
      sections.push(`- ${warning}`);
    }
  }

  return `${sections.join('\n')}\n`;
}

export async function emit(ir: IR, options: EmitterOptions): Promise<void> {
  if (options.adapter !== 'mcp') {
    throw new Error(`Unsupported emitter adapter: ${options.adapter}`);
  }

  checkNameCollisions(ir.operations.map((operation) => operation.name));

  const operations = ir.operations.map((operation) => {
    const typeName = toTypeName(operation.name);

    return {
      rawName: operation.name,
      description: operation.description,
      methodName: toMethodName(operation.name),
      typeName,
      inputTypeName: `${typeName}Input`,
      outputTypeName: operation.outputSchema ? `${typeName}Output` : undefined,
    } satisfies EmittedOperation;
  });

  const srcDir = path.join(options.outDir, 'src');
  const typesFile = await renderTypesFile(ir, operations);
  const clientFile = renderClientFile(options, operations);
  const packageJson = renderPackageJson(options);
  const tsconfig = renderTsConfig();
  const readme = renderReadme(options, operations);

  await mkdir(srcDir, { recursive: true });
  await Promise.all([
    writeFile(path.join(options.outDir, 'package.json'), packageJson, 'utf8'),
    writeFile(path.join(options.outDir, 'tsconfig.json'), tsconfig, 'utf8'),
    writeFile(path.join(options.outDir, 'README.md'), readme, 'utf8'),
    writeFile(path.join(srcDir, 'types.ts'), typesFile, 'utf8'),
    writeFile(path.join(srcDir, 'client.ts'), clientFile, 'utf8'),
  ]);
}
